"use client";

import * as React from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Sparkles, ArrowRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export function AiConsultant({ aiSummary }: { aiSummary: string | null }) {
  if (!aiSummary) {
    return (
      <Card className="border-indigo-200 dark:border-indigo-900 bg-indigo-50/50 dark:bg-indigo-950/10">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center text-xl text-indigo-800 dark:text-indigo-400">
                <Sparkles className="mr-2 h-5 w-5" />
                AI SEO Consultant
              </CardTitle>
              <CardDescription>Expert insights generated by AI</CardDescription>
            </div>
            <Badge variant="outline" className="text-indigo-600 border-indigo-200">Processing</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">No AI summary generated for this audit. Make sure your API key is configured.</p>
        </CardContent>
      </Card>
    );
  }

  // Very basic markdown parsing for headers and lists
  const renderText = (text: string) => {
    return text.split('\n').map((line, i) => {
      if (line.startsWith('### ')) {
        return <h4 key={i} className="text-md font-semibold mt-4 mb-2 text-indigo-900 dark:text-indigo-300">{line.replace('### ', '')}</h4>;
      }
      if (line.startsWith('## ')) {
        return <h3 key={i} className="text-lg font-bold mt-6 mb-3 text-indigo-950 dark:text-indigo-200">{line.replace('## ', '')}</h3>;
      }
      if (line.startsWith('# ')) {
        return <h2 key={i} className="text-xl font-bold mt-6 mb-3 text-indigo-950 dark:text-indigo-200">{line.replace('# ', '')}</h2>;
      }
      if (line.startsWith('- ') || line.startsWith('* ')) {
        return (
          <div key={i} className="flex items-start gap-2 ml-4 mb-1 text-sm text-indigo-800/80 dark:text-indigo-300/80">
            <ArrowRight className="h-3 w-3 mt-1 shrink-0" />
            <span>{line.substring(2)}</span>
          </div>
        );
      }
      if (line.trim() === '') return <div key={i} className="h-2" />;
      
      // Default paragraph
      return <p key={i} className="text-sm mb-2 text-indigo-900/90 dark:text-indigo-200/90 leading-relaxed">{line}</p>;
    });
  };

  return (
    <Card className="border-indigo-200 dark:border-indigo-900/50 bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-950/20 dark:to-purple-950/20 overflow-hidden relative">
      <div className="absolute top-0 right-0 p-32 bg-indigo-500/5 dark:bg-indigo-500/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none" />
      <CardHeader className="pb-3 relative z-10">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center text-xl text-indigo-800 dark:text-indigo-400">
              <Sparkles className="mr-2 h-5 w-5" />
              AI SEO Consultant
            </CardTitle>
            <CardDescription>Executive summary & growth opportunities</CardDescription>
          </div>
          <Badge className="bg-indigo-100 text-indigo-700 hover:bg-indigo-200 border-indigo-200 dark:bg-indigo-900 dark:text-indigo-300">
            Powered by AI
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="relative z-10">
        <div className="rounded-lg bg-white/50 dark:bg-black/20 p-6 border border-indigo-100 dark:border-indigo-800/30 backdrop-blur-sm">
          {renderText(aiSummary)}
        </div>
      </CardContent>
    </Card>
  );
}
